name: Test Operator Setup
on:
- push

jobs:
  test-lxd:
    runs-on: ubuntu-latest
    name: Setup lxd environment
    steps:
      - name: Check out code
        uses: actions/checkout@v2
      - uses: ./
        with:
          provider: lxd

      - name: Deploy ubuntu
        run: |
          juju deploy ubuntu
          juju status
          exit $?

  test-microk8s:
    runs-on: ubuntu-latest
    name: Setup microk8s environment
    steps:
      - uses: charmed-kubernetes/actions-operator@master
        with:
          provider: microk8s

      - name: Deploy minio
        run: |
          juju deploy cs:minio
          juju status
          exit $?

  test-aws:
    runs-on: self-hosted
    name: Setup operator environment for AWS
    steps:
      - name: Check out code
        uses: actions/checkout@v2
      - uses: ./
        with:
          provider: aws

      - name: Deploy ubuntu
        run: |
          juju deploy ubuntu
          juju status
          exit $?