name: Test Operator Setup
on:
- push

jobs:
  test-lxd:
    runs-on: ubuntu-latest
    name: Setup operator environment
    steps:
      - uses: charmed-kubernetes/actions-operator@master
        with:
          provider: lxd

      - name: Deploy ubuntu
        run: |
          juju deploy ubuntu
          juju status
          exit $?

  test-microk8s:
    runs-on: ubuntu-latest
    name: Setup operator environment
    steps:
      - uses: charmed-kubernetes/actions-operator@master
        with:
          provider: microk8s

      - name: Deploy minio
        run: |
          juju deploy cs:minio
          juju status
          exit $?
